=== HL7/fhir/tools/schema/mappingExceptions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mappingExceptions">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="unmappedElement">
          <xs:complexType>
            <xs:attribute name="patternPath" use="required" type="Path"/>
            <xs:attribute name="reason" use="optional">
              <xs:simpleType>
                <xs:union memberTypes="UnmappedReasons NonEmptyString"/>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="doubleMappedElement">
          <xs:complexType>
            <xs:attribute name="patternPath" use="required" type="Path"/>
            <xs:attribute name="reason" use="optional">
              <xs:simpleType>
                <xs:union memberTypes="DoubleMappedReasons NonEmptyString"/>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="divergentElement">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="shortUnmatched" type="LongStringDifference"/>
              <xs:element name="definitionUnmatched" type="LongStringDifference"/>
              <xs:element name="commentsUnmatched" type="LongStringDifference"/>
              <xs:element name="requirementsUnmatched" type="LongStringDifference"/>
              <xs:element name="lowerCardinality">
                <xs:complexType mixed="true">
                  <xs:attribute name="_pattern" use="required" type="LowerCardinality"/>
                  <xs:attribute name="_resource" use="required" type="LowerCardinality"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="LowerCardinalityReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="upperCardinality">
                <xs:complexType mixed="true">
                  <xs:attribute name="_pattern" use="required" type="UpperCardinality"/>
                  <xs:attribute name="_resource" use="required" type="UpperCardinality"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="UpperCardinalityReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="modifier">
                <xs:complexType mixed="true">
                  <xs:attribute name="_pattern" use="required" type="xs:boolean"/>
                  <xs:attribute name="_resource" use="required" type="xs:boolean"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="ModifierReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="summary">
                <xs:complexType mixed="true">
                  <xs:attribute name="_pattern" use="required" type="xs:boolean"/>
                  <xs:attribute name="_resource" use="required" type="xs:boolean"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="SummaryReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="bindingExistence">
                <xs:complexType mixed="true">
                  <xs:attribute name="_pattern" type="xs:string" use="required"/>
                  <xs:attribute name="_resource" type="xs:string" use="required"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="BindingExistenceReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="bindingStrength">
                <xs:complexType mixed="true">
                  <xs:attribute name="_pattern" type="xs:string" use="required"/>
                  <xs:attribute name="_resource" type="xs:string" use="required"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="BindingStrengthReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="bindingSystems">
                <xs:complexType mixed="true">
                  <xs:attribute name="_pattern" type="xs:string" use="required"/>
                  <xs:attribute name="_resource" type="xs:string" use="required"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="BindingSystemReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="missingTypes">
                <xs:complexType mixed="true">
                  <xs:attribute name="_pattern" use="required" type="DataType"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="MissingTypeReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="extraTypes">
                <xs:complexType mixed="true">
                  <xs:attribute name="_resource" use="required" type="DataType"/>
                  <xs:attribute name="reason" use="optional">
                    <xs:simpleType>
                      <xs:union memberTypes="ExtraTypeReasons NonEmptyString"/>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:choice>
            <xs:attribute name="patternPath" use="required" type="Path"/>
            <xs:attribute name="resourcePath" use="required" type="Path"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
      <xs:attribute name="pattern" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="resource" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
	</xs:element>
	<xs:complexType name="LongStringDifference" mixed="true">
    <xs:sequence>
      <xs:element name="_pattern" type="ValueString" minOccurs="1" maxOccurs="1"/>
      <xs:element name="resource" type="ValueString" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
		<xs:attribute name="reason" use="optional">
      <xs:simpleType>
        <xs:union memberTypes="LongStringReasons NonEmptyString"/>
      </xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="LongStringReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="Incorporates content from profile with context-specific wording"/>
      <xs:enumeration value="Pattern language does not apply in this context"/>
      <xs:enumeration value="Removed information not relevant to this resource"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="UnmappedReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="Not relevant for this resource"/>
      <xs:enumeration value="If captured, represented using Provenance"/>
      <xs:enumeration value="Implicit for this resource"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="DoubleMappedReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="Resource element(s) and extension(s) cover different types"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="LowerCardinalityReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="In this resource, this element will always be known in all contexts"/>
      <xs:enumeration value="There are multiple elements and constraints ensure at least one is present"/>
      <xs:enumeration value="The resource scope is broader than the pattern assumptions and this element will not always be known"/>
      <xs:enumeration value="The parent element makes this element effectively optional"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="UpperCardinalityReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="In this resource, the element cannot ever repeat, regardless of context"/>
      <xs:enumeration value="In this resource, multiple repetitions are possible"/>
      <xs:enumeration value="The parent element makes this element effectively repeating"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="ModifierReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="The codes that made this element a modifier are not used for this resource"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="SummaryReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="While relevent in most resources, this element is not needed in summaries for this resource"/>
      <xs:enumeration value="While not relevent in most resources, this element is important to appear in summaries for this resource"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="MissingTypeReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="The missing type(s) never apply in any context where this resource is used"/>
      <xs:enumeration value="The scope of the resource is being broadened to a more generic type"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="ExtraTypeReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="The scope of the resource is being narrowed to more specific types - the other types possible in the pattern would never be used for this resource"/>
      <xs:enumeration value="The specific data types used have been changed to reflect the narrower usage relevant for this resource"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="BindingExistenceReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="While a binding could not be defined at the pattern level, the resource is specific enough to allow a binding"/>
      <xs:enumeration value="The data type that is bound in the pattern is not used for this resource element"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="BindingStrengthReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="The narrower context of the resource makes a tighter binding appropriate"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="BindingSystemReasons">
    <xs:restriction base="NonEmptyString">
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="This resource requires additional codes not covered in the original binding"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:complexType name="ValueString">
		<xs:attribute name="value" use="required" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="NonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Path">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Za-z]+(\.[A-Za-z]+)*(\[x\])?"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DataType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z0-9]+(\([A-Za-z]+(,\s*[A-Za-z]+)*\))?(,\s*[A-Za-z0-9]+(\([A-Za-z]+(,\s*[A-Za-z]+)*\))?)*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="LowerCardinality">
    <xs:restriction base="xs:string">
      <xs:pattern value="[01]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpperCardinality">
    <xs:restriction base="xs:string">
      <xs:pattern value="[1\*]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== HL7/fhir/source/devicerequest/devicerequest-fivews-mapping-exceptions.xml
<mappingExceptions pattern="FiveWs" resource="DeviceRequest"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tools/schema/mappingExceptions.xsd">
    <!--For information on the contents of this file and how to properly update it, see https://confluence.hl7.org/display/FHIR/Mapping+to+Patterns.-->
    <divergentElement patternPath="FiveWs.class" resourcePath="DeviceRequest.intent">
        <modifier _pattern="false" _resource="true" reason="Unknown"/>
    </divergentElement>
    <divergentElement patternPath="FiveWs.what[x]" resourcePath="DeviceRequest.parameter">
        <upperCardinality _pattern="1" _resource="*" reason="Unknown"/>
    </divergentElement>
    <unmappedElement patternPath="FiveWs.cause" reason="Unknown"/>
    <unmappedElement patternPath="FiveWs.version" reason="Unknown"/>
    <unmappedElement patternPath="FiveWs.witness" reason="Unknown"/>
    <unmappedElement patternPath="FiveWs.where" reason="Unknown"/>
    <unmappedElement patternPath="FiveWs.init" reason="Unknown"/>
    <unmappedElement patternPath="FiveWs.source" reason="Unknown"/>
    <unmappedElement patternPath="FiveWs.who" reason="Unknown"/>
    <unmappedElement patternPath="FiveWs.done" reason="Unknown"/>
</mappingExceptions>

=== HL7/fhir/source/coverageeligibilityresponse/coverageeligibilityresponse-event-mapping-exceptions.xml
<mappingExceptions pattern="Event"
    resource="CoverageEligibilityResponse"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tools/schema/mappingExceptions.xsd">
    <!--For information on the contents of this file and how to properly update it, see https://confluence.hl7.org/display/FHIR/Mapping+to+Patterns.-->
    <divergentElement patternPath="Event.identifier" resourcePath="CoverageEligibilityResponse.identifier">
        <summary _pattern="true" _resource="false" reason="Unknown"/>
        <shortUnmatched reason="Unknown">
            <_pattern value="Business identifier for coverage eligibility response"/>
            <resource value="Business Identifier for coverage eligiblity request"/>
        </shortUnmatched>
        <definitionUnmatched reason="Unknown">
            <_pattern value="Business identifiers assigned to this coverage eligibility response by the performer and/or other systems.  These identifiers remain constant as the resource is updated and propagates from server to server."/>
            <resource value="A unique identifier assigned to this coverage eligiblity request."/>
        </definitionUnmatched>
        <commentsUnmatched reason="Unknown">
            <_pattern value="Note: This is a business identifier, not a resource identifier (see [discussion](resource.html#identifiers)).  It is best practice for the identifier to only appear on a single resource instance, however business practices may occasionally dictate that multiple resource instances with the same identifier can exist - possibly even with different resource types.  For example, multiple Patient and a Person resource instance might share the same social insurance number."/>
            <resource value=""/>
        </commentsUnmatched>
        <requirementsUnmatched reason="Unknown">
            <_pattern value="Allows identification of the coverage eligibility response as it is known by various participating systems and in a way that remains consistent across servers."/>
            <resource value="Allows coverage eligibility requests to be distinguished and referenced."/>
        </requirementsUnmatched>
    </divergentElement>
    <divergentElement patternPath="Event.basedOn" resourcePath="CoverageEligibilityResponse.request">
        <lowerCardinality _pattern="0" _resource="1" reason="Unknown"/>
        <upperCardinality _pattern="*" _resource="1" reason="Unknown"/>
        <missingTypes _pattern="Reference(Request)" reason="Unknown"/>
        <extraTypes _resource="Reference(CoverageEligibilityRequest)" reason="Unknown"/>
        <shortUnmatched reason="Unknown">
            <_pattern value="Fulfills plan, proposal or order"/>
            <resource value="Eligibility request reference"/>
        </shortUnmatched>
        <definitionUnmatched reason="Unknown">
            <_pattern value="A plan, proposal or order that is fulfilled in whole or in part by this coverage eligibility response."/>
            <resource value="Reference to the original request resource."/>
        </definitionUnmatched>
        <requirementsUnmatched reason="Unknown">
            <_pattern value="Allows tracing of authorization for the coverage eligibility response and tracking whether proposals/recommendations were acted upon."/>
            <resource value="Needed to allow the response to be linked to the request."/>
        </requirementsUnmatched>
    </divergentElement>
    <divergentElement patternPath="Event.status" resourcePath="CoverageEligibilityResponse.status">
        <shortUnmatched reason="Unknown">
            <_pattern value="preparation | in-progress | not-done | suspended | aborted | completed | entered-in-error | unknown"/>
            <resource value="active | cancelled | draft | entered-in-error"/>
        </shortUnmatched>
        <definitionUnmatched reason="Unknown">
            <_pattern value="The current state of the coverage eligibility response."/>
            <resource value="The status of the resource instance."/>
        </definitionUnmatched>
        <commentsUnmatched reason="Unknown">
            <_pattern value="A nominal state-transition diagram can be found in the (Event pattern documentation&#xa;&#xa;Unknown does not represent &quot;other&quot; - one of the defined statuses must apply.  Unknown is used when the authoring system is not sure what the current status is."/>
            <resource value="This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid."/>
        </commentsUnmatched>
    </divergentElement>
    <divergentElement patternPath="Event.subject" resourcePath="CoverageEligibilityResponse.patient">
        <missingTypes _pattern="Reference(Group)" reason="Unknown"/>
        <shortUnmatched reason="Unknown">
            <_pattern value="Individual service was done for/to"/>
            <resource value="Intended recipient of products and services"/>
        </shortUnmatched>
        <definitionUnmatched reason="Unknown">
            <_pattern value="The individual or set of individuals the action is being or was performed on."/>
            <resource value="The party who is the beneficiary of the supplied coverage and for whom eligibility is sought."/>
        </definitionUnmatched>
        <requirementsUnmatched reason="Unknown">
            <_pattern value="Links the coverage eligibility response to the Patient context.  May also affect access control."/>
            <resource value="Required to provide context and coverage validation."/>
        </requirementsUnmatched>
    </divergentElement>
    <divergentElement patternPath="Event.note" resourcePath="CoverageEligibilityResponse.disposition">
        <upperCardinality _pattern="*" _resource="1" reason="Unknown"/>
        <missingTypes _pattern="Annotation" reason="Unknown"/>
        <extraTypes _resource="string" reason="Unknown"/>
        <shortUnmatched reason="Unknown">
            <_pattern value="Comments made about the event"/>
            <resource value="Disposition Message"/>
        </shortUnmatched>
        <definitionUnmatched reason="Unknown">
            <_pattern value="Comments made about the coverage eligibility response by the performer, subject or other participants."/>
            <resource value="A human readable description of the status of the adjudication."/>
        </definitionUnmatched>
    </divergentElement>
    <unmappedElement patternPath="Event.partOf" reason="Unknown"/>
    <unmappedElement patternPath="Event.reported" reason="Unknown"/>
    <unmappedElement patternPath="Event.reason" reason="Unknown"/>
    <unmappedElement patternPath="Event.relevantHistory" reason="Unknown"/>
    <unmappedElement patternPath="Event.code" reason="Unknown"/>
    <unmappedElement patternPath="Event.location" reason="Unknown"/>
    <unmappedElement patternPath="Event.statusReason" reason="Unknown"/>
    <unmappedElement patternPath="Event.performer.actor" reason="Unknown"/>
    <unmappedElement patternPath="Event.performer.function" reason="Unknown"/>
    <unmappedElement patternPath="Event.category" reason="Unknown"/>
    <unmappedElement patternPath="Event.encounter" reason="Unknown"/>
    <unmappedElement patternPath="Event.recorded" reason="Unknown"/>
    <unmappedElement patternPath="Event.occurrence" reason="Unknown"/>
    <unmappedElement patternPath="Event.product" reason="Unknown"/>
    <unmappedElement patternPath="Event.performer" reason="Unknown"/>
    <unmappedElement patternPath="Event.researchStudy" reason="Unknown"/>
</mappingExceptions>
